spring.application.name=backend

# PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-icy-band-ac4jq3y6.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#O que mudou em relação ao H2
#
#ddl-auto=update em vez de create-drop — agora os dados persistem entre reinicializações
#URL aponta pro Neon em vez do H2 em memória
#Dialect específico do PostgreSQL